---
title: "Introduction to R Programming"
site: distill::distill_website
---



Welcome to the website for Introduction to R Programming!  

This website contains course materials and outside resources for an introductory R programming course.

# Website Content

The <span style = 'color: #a6873b;'>**Schedule**</span> section provides a schedule of topics and links to supplemental resources.  

The <span style = 'color: #a6873b;'>**Resources**</span> heading lists several helpful resources for R learners.  R for Data Science will serve as the primary text for this course.  It's available for [free online](https://r4ds.had.co.nz/){target="_blank"}, but well-worth the cost for the [paper copy](https://www.amazon.com/Data-Science-Transform-Visualize-Model/dp/1491910399/ref=sr_1_1?crid=UJMS0UH3O9KN&keywords=r+for+data+science&qid=1650063947&sprefix=r+for+data+scienc%2Caps%2C201&sr=8-1){target="_blank"}.

The <span style = 'color: #a6873b;'>**Modules**</span> heading contains most of the course lecture content.  You'll find all presentations/lecture notes here.

The <span style = 'color: #a6873b;'>**Project Problems**</span> heading contains all of the practice projects problems.

The <span style = 'color: #a6873b;'>**Project Solutions**</span> heading contains all of the solutions to the practice projects problems.  I'll add these solutions to the website about 24 hours before the next week's lecture so that you have an opportunity to try out the problems yourself before viewing the solutions.

# Lectures

Lectures will take place via Zoom every DAY at TIME PST.