---
title: "Schedule"
output: distill::distill_article
---

```{=html}
<style>
d-article table td {
  border-bottom: 1px solid rgba(4, 4, 4, 0.36);
}
</style>
```
```{=html}
<style>
d-article table tbody :first-child td {
  padding-top: 2px;
  border-top: 3px solid rgba(4, 4, 4, 0.7);
}
</style>
```
```{=html}
<style>
d-article table tbody :last-child td {
  padding-top: 2px;
  border-bottom: 2px solid rgba(4, 4, 4, 0.7);
}
</style>
```
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| Module | Topic                                      | Additional Reading                                                                                                        | Additional Videos                                                                           |
+========+============================================+===========================================================================================================================+=============================================================================================+
| 1      | Overview                                   | [Installing R and R Studio](https://rstudio-education.github.io/hopr/starting.html){target="_blank"}                      |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [Modern Dive - Chapter 1](https://moderndive.com/1-getting-started.html){target="_blank"}                                 |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 2      | Base R                                     | [Base R Cheat Sheet](https://iqss.github.io/dss-workshops/R/Rintro/base-r-cheat-sheet.pdf){target="_blank"}               |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [HOPwR Chapters 1 - 3](https://rstudio-education.github.io/hopr/){target="_blank"}                                        |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 3      | Data Visualization - 1                     | [ggplot2 Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf){target="_blank"} | [Thomas Lin Pedersen Webinar](https://www.youtube.com/watch?v=h29g21z0a68){target="_blank"} |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [RfDS Chapter 3](https://r4ds.had.co.nz/data-visualisation.html){target="_blank"}                                         |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 4      | Workflows/Style Guide/Directory Structures | [Style Guide](http://adv-r.had.co.nz/Style.html){target="_blank"}                                                         |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [Project-Oriented Workflows](https://rstats.wtf/project-oriented-workflow.html){target="_blank"}                          |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 5      | Data Transformation                        | [dplyr Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-transformation.pdf){target="_blank"}  |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [RfDS Chapter 5](https://r4ds.had.co.nz/transform.html){target="_blank"}                                                  |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 6      | Exploratory Data Analysis                  | [RfDS Chapter 7](https://r4ds.had.co.nz/exploratory-data-analysis.html){target="_blank"}                                  |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 7      | Tibbles/Data Frames                        | [RfDS Chapter 10](https://r4ds.had.co.nz/tibbles.html){target="_blank"}                                                   |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 8      | Data Import                                | [Data Import Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-import.pdf){target="_blank"}    |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [RfDS Chapter 11](https://r4ds.had.co.nz/data-import.html){target="_blank"}                                               |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 9      | Tidy Data                                  | [tidyr Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/tidyr.pdf){target="_blank"}                |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [RfDS Chapter 12](https://r4ds.had.co.nz/tidy-data.html){target="_blank"}                                                |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 10     | Relational Data                            | [dplyr Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-transformation.pdf){target="_blank"}  |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [RfDS Chapter 13](https://r4ds.had.co.nz/relational-data.html){target="_blank"}                                           |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 11     | Strings                                    | [stringr Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/strings.pdf){target="_blank"}            |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [RfDS Chapter 14](https://r4ds.had.co.nz/strings.html){target="_blank"}                                                   |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 12     | Factors                                    | [forcats Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/factors.pdf){target="_blank"}            |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [RfDS Chapter 15](https://r4ds.had.co.nz/factors.html){target="_blank"}                                                   |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 13     | Data Visualization - 2                     | [RfDS Chapter 28](https://r4ds.had.co.nz/graphics-for-communication.html){target="_blank"}                                |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+
| 14     | R Markdown                                 | [R Markdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf){target="_blank"}    |                                                                                             |
|        |                                            |                                                                                                                           |                                                                                             |
|        |                                            | [fFDS Chapter 27](https://r4ds.had.co.nz/r-markdown.html){target="_blank"}                                                |                                                                                             |
+--------+--------------------------------------------+---------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------+

RfDS = R for Data Science

HOPwR = Hand-On Programming with R
